### ISSUE TITLE
Website redesign ideas

### ISSUE THREAD

**Issue by maxfell** [upfrontug/upfrontug.github.io#18]
- [ ] Add a "I want to speak" page with information about learning more, coaching, our goals, and a form to apply
- [ ] Find a nice looking way to embed videos
- [ ] Add photos of the speakers
- [ ] Add a more appealing top banner (maybe a blurred photo with our logo on top of it)

**Comment by Kriesse** [comment]
Closing, most of it's done. Let's open separate, actionable issues.
