### ISSUE TITLE
Move to organization

### ISSUE THREAD

**Issue by rmehner** [upfrontug/upfrontug.github.io#35]
Once the march meetup is over I'll move this repo to the @upfrontug (all other user names have been taken already) organization. In theory this should be easy and smoothly. But to not interfere with the announcements I'll do it next week after the meetup.

@Kriesse @espy @QateOh @maxfell, you've been invited to the orga.

**Comment by QateOh** [comment]
Thank you @rmehner .

**Comment by rmehner** [comment]
This is done now :) Everyone should be invited and the website just continued to run as before.
