### ISSUE TITLE
Add technical speaks to speakers guide page

### ISSUE THREAD

**Issue by maxfell** [upfrontug/upfrontug.github.io#7]
We need a list of technical equipment provided at co.up and anything else a speaker may want to know about.

**Comment by maxfell** [comment]
Who can collect the necessary information? @espy?

**Comment by rmehner** [comment]
Projector: http://www.epson.com/cgi-bin/Store/jsp/Product/Specifications.do?sku=V11H367120, Native Resolution: 1280x800 (WXGA)

Connectors: HDMI and VGA.
If you use OSX >= 10.8 you can use Airplay to use the projector.

Wireless headset microphone available
Hand microphone available too (you can even use both at the same time)

You can use the speakers either via Airplay (make sure you connect the optical out from the AppleTV to the mixer) or just by using a separate cable.

Anything else?

**Comment by maxfell** [comment]
Thanks for being quick!
